# ~~~~~~~~~
# hugo æœ¬èº«çš„é…ç½®
# ~~~~~~~~~
baseURL: "https://zhroc.github.io/" # ä¸»ç«™çš„ URL
title: zhroc's Blog # ç«™ç‚¹æ ‡é¢˜
#copyright: "[zhroc's Blog](https://zhroc.github.io/)" # ç½‘ç«™çš„ç‰ˆæƒå£°æ˜ï¼Œé€šå¸¸æ˜¾ç¤ºåœ¨é¡µè„š
theme: PaperMod # ä¸»é¢˜
languageCode: zh-cn # è¯­è¨€

enableInlineShortcodes: true # shortcodeï¼Œç±»ä¼¼äºæ¨¡æ¿å˜é‡ï¼Œå¯ä»¥åœ¨å†™ markdown çš„æ—¶å€™ä¾¿æ·åœ°æ’å…¥ï¼Œå®˜æ–¹æ–‡æ¡£ä¸­æœ‰ä¸€ä¸ªè§†é¢‘è®²çš„å¾ˆé€šä¿—
hasCJKLanguage: true # æ˜¯å¦æœ‰ CJK çš„å­—ç¬¦
enableRobotsTXT: true # å…è®¸ç”Ÿæˆ robots.txt
buildDrafts: false # æ„å»ºæ—¶æ˜¯å¦åŒ…æ‹¬è‰ç¨¿
buildFuture: false # æ„å»ºæœªæ¥å‘å¸ƒçš„å†…å®¹
buildExpired: false # æ„å»ºè¿‡æœŸçš„å†…å®¹

enableEmoji: true # å…è®¸ emoji
pygmentsUseClasses: true #ä½¿ç”¨CSSæ¸²æŸ“è¯­æ³•é«˜äº®
defaultContentLanguage: zh # é¡¶éƒ¨é¦–å…ˆå±•ç¤ºçš„è¯­è¨€ç•Œé¢
defaultContentLanguageInSubdir: false # æ˜¯å¦åœ¨urlåŠ ä¸Š/zh

languages:
  zh:
    languageName: "ä¸­æ–‡" # å±•ç¤ºçš„è¯­è¨€å
    weight: 1 # æƒé‡
    taxonomies: # åˆ†ç±»ç³»ç»Ÿ
      category: categories
      tag: tags
      # series: series #ä¸ä½¿ç”¨
    # https://gohugo.io/content-management/menus/#define-in-site-configuration
    menus:
      main:
        - name: Home
          pageRef: /
          weight: 10 # æ§åˆ¶åœ¨é¡µé¢ä¸Šå±•ç¤ºçš„å‰åé¡ºåº
        - name: Posts
          pageRef: posts/
          weight: 20
        - name: Archives
          pageRef: archives/
          weight: 30
        - name: Search
          pageRef: search/
          weight: 40
        - name: About
          pageRef: about/
          weight: 50

# ~~~~~~~~~
# ä¸»é¢˜çš„é…ç½®(åŸºæœ¬ä¸Šæ˜¯)
# ~~~~~~~~~
pagination:
  pagerSize: 8 # æ¯é¡µå±•ç¤ºçš„æ–‡ç« æ•°é‡ï¼Œè¿™ä¸ªæ²¡æ‰¾åˆ°æ–‡æ¡£ï¼Œåº”è¯¥æ˜¯ä¸»é¢˜è‡ªå·±è®¾ç½®çš„


# è¿™é‡Œçš„å‚æ•°ä¼šè¢«ä»£ç ä»¥ .Site.Params çš„å½¢å¼è¯»å–
params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "zhroc's Blog - https://zhroc.github.io"
  author: zhroc
  defaultTheme: auto # light or  dark 
  ShowShareButtons: false # æ˜¯å¦å±•ç¤ºåˆ†äº«çš„æŒ‰é’®
  disableLanguageSwitcher: true  # ç¦ç”¨è¯­è¨€åˆ‡æ¢æŒ‰é’®
  
  displayFullLangName: false # æ˜¯å¦å±•ç¤ºè¯­è¨€å…¨å
  ShowPostNavLinks: true # å±•ç¤ºåº•éƒ¨æ–‡ç« å¯¼èˆª
  ShowBreadCrumbs: false # æ˜¯å¦å±•ç¤ºæ ‡é¢˜ä¸Šæ–¹çš„é¢åŒ…å±‘
  ShowCodeCopyButtons: true # æ˜¯å¦å±•ç¤ºå¤åˆ¶ä»£ç çš„æŒ‰é’®
  ShowRssButtonInSectionTermList: false # RSS ç›¸å…³
  ShowAllPagesInArchive: true # åœ¨å½’æ¡£é¡µé¢å±•ç¤ºæ‰€æœ‰çš„é¡µé¢
  ShowPageNums: false # å±•ç¤ºé¡µé¢çš„é¡µæ•°
  enablePhotoSwipe: false  # å¯ç”¨å›¾ç‰‡ç‚¹å‡»æ”¾å¤§

  ShowReadingTime: true # å±•ç¤ºé¢„ä¼°çš„é˜…è¯»æ—¶é•¿
  ShowWordCounts: false # å±•ç¤ºæ–‡ç« å­—æ•°
  ShowLastMod: false #æ˜¾ç¤ºæ–‡ç« æ›´æ–°æ—¶é—´

  images: [""] # ç¼ºçœçš„å›¾ç‰‡ï¼Œæ¯”å¦‚ï¼Œåšå®¢çš„å°é¢
  DateFormat: "2006-01-02" # è¿™ä¸ªæ—¶é—´æ˜¯ä½œè€…è‡ªå·±å†™çš„ï¼Œåªèƒ½è¿™æ ·å†™

  ShowToc: true # å±•ç¤ºæ–‡ç« è¯¦æƒ…é¡µçš„ç›®å½•
  TocOpen: true # è‡ªåŠ¨å±•å¼€ç›®å½•
  comments: false # è¯„è®º

  profileMode:
    enabled: true
    title: ã€Œ It's a road roller! ã€
    subtitle:
    # subtitle: "æœ‰ç©ºå†æ›´~<br/>ğŸ‘‡è”ç³»æ–¹å¼"
    imageUrl: "https://avatars.githubusercontent.com/u/46491966"
    imageTitle: ""
    imageWidth: 150
    imageHeight: 150

  socialIcons:
    - name: github
      url: "https://github.com/zhroc"
    - name: twitter
      url: ""
    - name: facebook
      url: ""
    - name: email
      url: ""
    - name: RSS
      url: "index.xml"


  # æœç´¢
  fuseOpts:
      isCaseSensitive: false # æ˜¯å¦å¤§å°å†™æ•æ„Ÿ
      shouldSort: true # æ˜¯å¦æ’åº
      location: 0
      distance: 1000
      threshold: 0.4
      minMatchCharLength: 0
      # limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
      keys: ["title", "permalink", "summary", "content"]
      includeMatches: true

  # è®¾ç½®ç½‘ç«™çš„æ ‡ç­¾é¡µçš„å›¾æ ‡ï¼Œå³ favicon
  assets:
      favicon: "favicon.png"
      favicon16x16: "favicon.png"
      favicon32x32: "favicon.png"
      apple_touch_icon: "favicon.png"
      safari_pinned_tab: "favicon.png"
      disableHLJS: true


  # footeré…ç½®
  StartYear: 2020 # åº•éƒ¨å¼€å§‹å¹´ä»½
  FilingNo: Moe ICP 20200608 # åº•éƒ¨å¤‡æ¡ˆå·

  # è‡ªå®šä¹‰å‚æ•°
  imgBaseURL: "https://webp.cooleryue.cn/" # å›¾åºŠï¼Œurlæœ«å°¾åŠ ä¸Šâ€œ/â€ï¼Œåˆ™mdä¸éœ€è¦åŠ ã€‚



  # --------------------------------------------------------------------paramså‚æ•°åˆ°æ­¤ç»“æŸã€‚


# https://github.com/adityatelange/hugo-PaperMod/wiki/Features#search-page
outputs:
  home:
    - HTML # ç”Ÿæˆçš„é™æ€é¡µé¢
    - RSS # è¿™ä¸ªå…¶å®æ— æ‰€è°“
    - JSON # necessary for search, è¿™é‡Œçš„é…ç½®ä¿®æ”¹å¥½ä¹‹åï¼Œä¸€å®šè¦é‡æ–°ç”Ÿæˆä¸€ä¸‹

markup:
  goldmark:
    renderer:
      unsafe: true # å¯ä»¥ unsafeï¼Œæœ‰äº› html æ ‡ç­¾å’Œæ ·å¼å¯èƒ½éœ€è¦
  highlight:
    anchorLineNos: false # ä¸è¦ç»™è¡Œå·è®¾ç½®é”šæ ‡
    codeFences: true # ä»£ç å›´æ 
    noClasses: false # TODO: ä¸çŸ¥é“å¹²å•¥çš„ï¼Œæš‚æ—¶æ²¡å¿…è¦äº†è§£ï¼Œä¸å½±å“å±•ç¤º
    lineNos: false # ä»£ç è¡Œ
    lineNumbersInTable: false # ä¸è¦è®¾ç½®æˆ trueï¼Œå¦åˆ™å¦‚æœæ–‡ç« å¼€å¤´æ˜¯ä»£ç çš„è¯ï¼Œæ‘˜è¦ä¼šç”±ä¸€å¤§å †æ•°å­—(å³ä»£ç è¡Œå·)å¼€å¤´æ–‡ç« 
    # è¿™é‡Œè®¾ç½® style æ²¡ç”¨ï¼Œå¾—è‡ªå·±åŠ  css
    # style: "github-dark"
    # style: monokai

